services:
    nextjs:
        image: vchecherynda/nextjs:latest
        container_name: nextjs
        ports:
            - '3000:80'

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - nextjs
