services:
  nextjs:
    image: vchecherynda/nextjs:latest
    container_name: nextjs
    ports:
      - "3000:80"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/dcalc.crt:/etc/nginx/ssl/dcalc.cert
      - ./ssl/dcalc.key:/etc/nginx/ssl/dcalc.key
    depends_on:
      - nextjs