services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner
    restart: always
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge