version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    depends_on:
      - nextjs