name: Deploy to DigitalOcean

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the latest code
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Log in to Docker Hub using secrets
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # - name: Build images
            #   run: |
            #       docker build -t nextjs-app .
            #       docker build -t nginx-app -t nginx:latest . -f nginx/Dockerfile

            # Build and push App Docker images to Docker Hub
            - name: Build and push App Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/deposit-calculator:latest

           # Build and push App Docker images to Docker Hub
            - name: Build and push Nginx Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            # Set up SSH
            - name: Install SSH client
              run: sudo apt-get install openssh-client

            - name: Add SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.DROPLET_HOST_ADRESS }}

            # Deploy the Docker container to the DigitalOcean droplet
            - name: Deploy Docker Container
              run: |
                  ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_HOST_ADRESS }} << EOF
                    docker images purge
                    docker pull ${{ secrets.DOCKER_USERNAME }}/deposit-calculator:latest

                    if docker ps -a --format '{{.Names}}' | grep -q '^deposit-calculator$'; then
                      docker stop deposit-calculator
                      docker rm deposit-calculator
                    fi

                    docker-compose up
                  EOF
