name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to the Docker hub
      id: docker-hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 

    - name: Build docker image
      id: build-docker-image
      run: |
        docker build . -f Dockerfile -t vchecherynda/nextjs:latest

    - name: Push docker image
      id: push-docker-image
      run: |
        docker push vchecherynda/nextjs:latest
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.DROPLET_HOST_ADRESS }}

    - name: Copy config files to Droplet
      env:
        DROPLET_IP: ${{ secrets.DROPLET_HOST_ADRESS }}
      run: |
        rsync -e "ssh bastion ssh" ./nginx.conf /etc/nginx/nginx.conf
        rsync -e "ssh bastion ssh" ./ssl/dcalc.crt /etc/nginx/ssl/dcalc.cert
        rsync -e "ssh bastion ssh" ./ssl/dcalc.key /etc/nginx/ssl/dcalc.key

    - name: Deploy to Droplet
      env:
        DROPLET_IP: ${{ secrets.DROPLET_HOST_ADRESS }}
      run: |
        ssh root@$DROPLET_IP << 'EOT'
          docker pull vchecherynda/nextjs:latest
          docker stop nextjs || true
          docker rm nextjs || true
          docker-compose up -d
        EOT