name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Docker image
      run: docker build -f Dockerfile.prod -t dcalc:${GITHUB_SHA} .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push image to Docker Hub
      run: |
        docker tag dcalc:${GITHUB_SHA} ${{ secrets.DOCKER_USERNAME }}/dcalc:${GITHUB_SHA}
        docker push ${{ secrets.DOCKER_USERNAME }}/dcalc:${GITHUB_SHA}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    
    steps:
    - name: Deploy to Digital Ocean droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST_ADRESS }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/dcalc:${GITHUB_SHA}
          docker-compose up -d
        debug: true


