name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to the Docker hub
      id: docker-hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $username -p $password 

    - name: Build docker image
      id: build-docker-image
      run: |
        docker build . -f Dockerfile -t vchecherynda/nextjs:${{ github.sha }}

    - name: Push docker image
      id: push-docker-image
      run: |
        docker push vchecherynda/nextjs:${{ github.sha }}
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.DROPLET_HOST_ADRESS }}
    
    - name: Deploy to Droplet
      env:
        DROPLET_IP: ${{ secrets.DROPLET_HOST_ADRESS }}
      run: |
        ssh root@$DROPLET_IP << 'ENDSSH'
          docker pull vchecherynda/nextjs:${{ github.sha }}
          docker stop nextjs-app || true
          docker rm nextjs-app || true
          docker-compose up -d
        ENDSSH